### ISSUE TITLE
Unable to import digital ocean resources

### ISSUE THREAD

**Issue by jordangarrison** [pulumi/pulumi-digitalocean#250]
Hi Pulumi Team,

Love this tool! Makes managing infrastructure easy and extensible.

Unfortunately, though I am unable to import any resources from DigitalOcean. I have attempted with both Droplets and Apps. I am running with Pulumi Verison: v3.9.1

## Steps to reproduce

1. Manually create a droplet
2. Get droplet id from console
3. Run import command `pulumi import digitalocean:index/droplet:Droplet [name] [id]

Expected: 

I expected to import the droplet into my IaC.

Actual: 

Recivied the following panic

```
pulumi import digitalocean:index/droplet:Droplet [name] [id] 
Previewing import (dev)

View Live: https://app.pulumi.com/jordangarrison/digitalocean/dev/previews/ab6062f1-dd83-4c51-b132-f6d8e12dac7d

     Type                           Name              Plan
     pulumi:pulumi:Stack            digitalocean-dev  running.
 =   └─ digitalocean:index:Droplet  droplet           import.
panic: interface conversion: schema.Type is *schema.ArrayType, not *schema.OptionalType

goroutine 134 [running]:
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindProperties(0xc000d76460, 0xc000aa0210, 0xc000abe000, 0x3, 0x4, 0x0, 0xc000522940, 0x7, 0x8, 0xc001967650, ...)
	/private/tmp/pulumi-20210730-79372-18z33h2/pkg/codegen/schema/schema.go:2005 +0xdd5
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindObjectTypeDetails(0xc000d76460, 0xc000ab9800, 0xc000aac030, 0x28, 0x0, 0x0, 0xc000aa0210, 0xc000a94490, 0x6, 0xc000abe000, ...)
	/private/tmp/pulumi-20210730-79372-18z33h2/pkg/codegen/schema/schema.go:2020 +0x117
github.com/pulumi/pulumi/pkg/v3/codegen/schema.bindTypes(0xc00097a140, 0xc00190b740, 0x5d4dcc0, 0xc00080e8d0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20210730-79372-18z33h2/pkg/codegen/schema/schema.go:2192 +0x9fd
github.com/pulumi/pulumi/pkg/v3/codegen/schema.importSpec(0xc000a19b50, 0xc, 0xc000a19b67, 0x5, 0xc000a1f720, 0x49, 0xc00190cce0, 0x2, 0x2, 0xc000810ed0, ...)
	/private/tmp/pulumi-20210730-79372-18z33h2/pkg/codegen/schema/schema.go:1398 +0x13b
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*pluginLoader).LoadPackage(0xc00080e8d0, 0xc0014a815e, 0xc, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20210730-79372-18z33h2/pkg/codegen/schema/loader.go:97 +0x30f
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*ImportStep).Apply(0xc0002a7a40, 0x1, 0x5a141ba, 0x23, 0xc0014c1dc0, 0x3)
	/private/tmp/pulumi-20210730-79372-18z33h2/pkg/resource/deploy/step.go:925 +0x464
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeStep(0xc0001b2600, 0x0, 0x5d94398, 0xc0002a7a40, 0x2, 0x2)
	/private/tmp/pulumi-20210730-79372-18z33h2/pkg/resource/deploy/step_executor.go:271 +0x209
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc0001b2600, 0x0, 0xc001599f20, 0x1, 0x1)
	/private/tmp/pulumi-20210730-79372-18z33h2/pkg/resource/deploy/step_executor.go:221 +0xef
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker(0xc0001b2600, 0x0, 0xc0014b7900)
	/private/tmp/pulumi-20210730-79372-18z33h2/pkg/resource/deploy/step_executor.go:365 +0x312
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.newStepExecutor
	/private/tmp/pulumi-20210730-79372-18z33h2/pkg/resource/deploy/step_executor.go:415 +0x24b
```

**Comment by stack72** [comment]
Hi @jordangarrison 

My apologies for the issue here - this is actually similar to another codegen issue I am working on right now so I hope to figure out that issue soon

Thanks

Paul

**Comment by stack72** [comment]
Hi @jordangarrison 

I'm sorry you hit this error, please can you try this with the latest version of the pulumi-digitalocean provider? I can't seem to recreate it 

Paul

**Comment by stack72** [comment]
Closing this out as we've not heard back from the original poster. If this is still an issue then we can reopen it
