### ISSUE TITLE
Unable to rollout converter

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-digitalocean#683]
### What happened?

From: https://github.com/pulumi/ci-mgmt/issues/889

This usually succeeds but trying it out here hits a panic at `make tfgen`.

First we get some warnings:

```
warning: %!(EXTRA string=Expected to pair --- begin/end for resource %v's Markdown header, string=digitalocean_monitor_alert)
warning: Expected an H1 in markdown for resource digitalocean_monitor_alert
warning: Found <elided> in description for [digitalocean_spaces_bucket_cors_configuration], but was able to preserve the examples. The description proper will be dropped in the Pulumi provider.
warning: Found <elided> in description for [digitalocean_spaces_bucket_policy], but was able to preserve the examples. The description proper will be dropped in the Pulumi provider.
warning: %!(EXTRA string=Expected to pair --- begin/end for resource %v's Markdown header, string=digitalocean_uptime_alert)
warning: Expected an H1 in markdown for resource digitalocean_uptime_alert
warning: %!(EXTRA string=Expected to pair --- begin/end for resource %v's Markdown header, string=digitalocean_uptime_check)
warning: Expected an H1 in markdown for resource digitalocean_uptime_check
warning: Found <elided> in description for [digitalocean_reserved_ip], but was able to preserve the examples. The description proper will be dropped in the Pulumi provider.
panic: fatal: error An assertion has failed: bulk converting examples failed. source error: convertViaPulumiCLI: pulumi command failed: exit sta
```

Then we get to this:

```
Converting from terraform...
panic: fatal: An assertion has failed: empty path part passed into getInfo

goroutine 71 [running]:

github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)

        /Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.105.0/go/common/util/contract/failfast.go:23

github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x1?, {0xf67ceff?, 0x57a05748?}, {0x0?, 0x2?, 0xc001261750?})

        /Users/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.105.0/go/common/util/contract/assert.go:35 +0xe8

github.com/pulumi/pulumi-converter-terraform/pkg/convert.(*scopes).getInfo.func1({0x0, 0x0}, 0x0, {0xc000afb570?, 0x2, 0x2})

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/pkg/convert/tf_scopes.go:191 +0xc5

github.com/pulumi/pulumi-converter-terraform/pkg/convert.(*scopes).getInfo.func1({0x0, 0x0}, 0x0, {0xc000afb560?, 0x3, 0x3})

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/pkg/convert/tf_scopes.go:225 +0x376

github.com/pulumi/pulumi-converter-terraform/pkg/convert.(*scopes).getInfo(0xc000ab8500, {0xc000d223c0, 0x30})

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/pkg/convert/tf_scopes.go:311 +0x743

github.com/pulumi/pulumi-converter-terraform/pkg/convert.(*scopes).pulumiName(0x10081ce0?, {0xc000d223c0?, 0xfeef100?})

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/pkg/convert/tf_scopes.go:316 +0x2a

github.com/pulumi/pulumi-converter-terraform/pkg/convert.convertObjectConsExpr(0xc0012638c8, 0x7?, 0xc000ab8500, {0xc001888160, 0x1e}, 0x1c?)

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/pkg/convert/tf.go:992 +0x1e5

github.com/pulumi/pulumi-converter-terraform/pkg/convert.convertExpression(0xfe35c01?, 0xd8?, 0xc0019b91d8?, {0xc001888160?, 0x16?}, {0x1007dee0?, 0xc0006817c0?})

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/pkg/convert/tf.go:1582 +0x2b6

github.com/pulumi/pulumi-converter-terraform/pkg/convert.convertBody(0xc0012638c8, 0xc000ab8500, {0xc001888140, 0x19}, {0x1007de00, 0xc0009daa50})

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/pkg/convert/tf.go:1854 +0x1768

github.com/pulumi/pulumi-converter-terraform/pkg/convert.convertManagedResources(0xc0012638c8, {0x10067fc8, 0xc000c022a0}, 0xc000ab8500, 0xc001d88600, 0xc000aca5b8)

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/pkg/convert/tf.go:2290 +0x13d4

github.com/pulumi/pulumi-converter-terraform/pkg/convert.translateModuleSourceCode(0xc001263e58, {0x1008d130, 0xc000758990}, {0xfc674c0, 0x1}, {0x1008d130, 0xc000758a50}, {0xfc674c0, 0x1}, {0x10067fc8, ...})

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/pkg/convert/tf.go:3026 +0x3985

github.com/pulumi/pulumi-converter-terraform/pkg/convert.TranslateModule(...)

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/pkg/convert/tf.go:3128

main.(*tfConverter).ConvertProgram.func1({0xc000b9a12c, 0x3}, {0xc000495200, 0x2dc})

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/cmd/pulumi-converter-terraform/main.go:103 +0x2fe

main.parTransformMapWith[...].func1()

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/cmd/pulumi-converter-terraform/par.go:56 +0x1ac

created by main.parTransformMapWith[...] in goroutine 25

        /Users/runner/work/pulumi-converter-terraform/pulumi-converter-terraform/cmd/pulumi-converter-terraform/par.go:53 +0xd5

error: rpc error: code = Unavailable desc = error reading from server: EOF
```

### Example

N/A

### Output of `pulumi about`

v3.112.0

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
I'll look into extracting the mappings and the specific example this fails on, this is not easy to debug.

**Comment by VenelinMartinov** [comment]
@t0yv0 I'll assign this to you for now, hope that's fine, let me know if you need help.

**Comment by t0yv0** [comment]
https://gist.github.com/t0yv0/980a311738ac109de02e28f0dbe3ac4f is the repro

**Comment by t0yv0** [comment]
I can't take this unfortunately but I'll open an issue to block on.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-converter-terraform/issues/145

**Comment by VenelinMartinov** [comment]
Much appreciated!

**Comment by mikhailshilkov** [comment]
Unmarking from blocked since the converter issue is fixed now

**Comment by t0yv0** [comment]
It's not released though @mikhailshilkov 

@pulumi/platform  can we get a quick release of https://github.com/pulumi/pulumi-converter-terraform much appreciated

**Comment by justinvp** [comment]
https://github.com/pulumi/pulumi-converter-terraform/pull/150

**Comment by t0yv0** [comment]
Fixed in https://github.com/pulumi/pulumi-digitalocean/commit/59545973392c701f5c08aab97778e432d89f6da2
