### ISSUE TITLE
Type mismatch between FirewallArgs.dropletIds and droplet.id

### ISSUE THREAD

**Issue by dkarter** [pulumi/pulumi-digitalocean#81]
When trying to create a firewall and assign it to a droplet I get a type mismatch:

```
TSError: ⨯ Unable to compile TypeScript:
    index.ts(34,71): error TS2345: Argument of type '{ inboundRules: { protocol: string; por
tRange: string; }[]; dropletIds: Pulumi.Output<string>[]; }' is not assignable to parameter
of type 'FirewallArgs'.
      Types of property 'dropletIds' are incompatible.
        Type 'Output<string>[]' is not assignable to type 'Input<number>[] | Promise<Input<n
umber>[]> | OutputInstance<Input<number>[]> | undefined'.
          Type 'Output<string>[]' is not assignable to type 'Input<number>[]'.
            Type 'Output<string>' is not assignable to type 'Input<number>'.
              Type 'Output<string>' is not assignable to type 'OutputInstance<number>'.
                Types of property 'apply' are incompatible.
                  Type '{ <U>(func: (t: string) => Promise<U>): Output<U>; <U>(func: (t: str
ing) => OutputInstance<U>): Output<U>; <U>(func: (t: string) => U): Output<...>; }' is not a
ssignable to type '{ <U>(func: (t: number) => Promise<U>): Output<U>; <U>(func: (t: number)
=> OutputInstance<U>): Output<U>; <U>(func: (t: number) => U): Output<...>; }'.
                    Types of parameters 'func' and 'func' are incompatible.
                      Types of parameters 't' and 't' are incompatible.
                        Type 'string' is not assignable to type 'number'.
```

<img width="911" alt="image" src="https://user-images.githubusercontent.com/551858/78329214-b864dd80-7546-11ea-9bc0-01f55aeec9bd.png">

I am happy to open a PR to fix this! Please let me know!

**Comment by dkarter** [comment]
that worked @leezen, thank you!

**Comment by leezen** [comment]
Thanks for confirming @dkarter 
I'm going to keep this issue open to indicate the actual bug hasn't been fixed yet.

**Comment by matthewswar** [comment]
Thank you for providing the workaround @leezen! For me, it's working great on deploying a fresh stack. However, once the stack is up, I'm running into issues with previewing and updating.
```ts
const mainFirewall = new digitalocean.Firewall(name('main-firewall'), {
    dropletIds: [mainDroplet.id.apply(parseInt)],
    // ...
    });
```

This will generate the following output:
```
Previewing update (hosting):
     Type                             Name                          Plan        Info
     pulumi:pulumi:Stack              mystack-hosting                       26 messages
 +-  ├─ digitalocean:index:Droplet    hosting-main-droplet          replace     [diff: ~userData]
 ~   ├─ digitalocean:index:DnsRecord  hosting-hosting-record-dnd    update      [diff: ~value]
 ~   ├─ digitalocean:index:DnsRecord  hosting-hosting-record-alias  update      [diff: ~value]
     └─ digitalocean:index:Firewall   hosting-main-firewall                     1 error

Diagnostics:
  digitalocean:index:Firewall (hosting-main-firewall):
    error: transport is closing

  pulumi:pulumi:Stack (mystack-hosting):
    panic: interface conversion: interface {} is string, not int
    goroutine 46 [running]:
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.SerializeValueForHash(0xc0004eacb0, 0x11f59e0, 0x16f8fa0, 0xc000187500)
        /home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.2.0/helper/schema/serialize.go:24 +0x953
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.HashSchema.func1(0x11f59e0, 0x16f8fa0, 0xd)
        /home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.2.0/helper/schema/set.go:43 +0x6f
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.visitPropertyValue(0xc00072f2f0, 0xb, 0xc0003e7f00, 0xa, 0x11d9280, 0xc0003d30e0, 0xc000187600, 0x0, 0x0, 0xc0004eb118)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.6.5/pkg/tfbridge/diff.go:140 +0xa61
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.doIgnoreChanges(0xc00017a750, 0xc000521530, 0xc00056a3c0, 0xc0005b5230, 0x0, 0x0, 0x0, 0xc0003d3e00)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.6.5/pkg/tfbridge/diff.go:281 +0x3df
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.(*Provider).Diff(0xc000510480, 0x1744a20, 0xc00056a330, 0xc000532540, 0xc000510480, 0x1289d01, 0xc0001c3800)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.6.5/pkg/tfbridge/provider.go:551 +0x7cc
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Diff_Handler.func1(0x1744a20, 0xc00056a330, 0x13ca920, 0xc000532540, 0x13e7ca0, 0x20ae8b0, 0x1744a20, 0xc00056a330)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.9.1/sdk/proto/go/provider.pb.go:1597 +0x8d
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1744a20, 0xc0002764b0, 0x13ca920, 0xc000532540, 0xc0000e7900, 0xc0000e7920, 0x0, 0x0, 0x171fca0, 0xc0003cd260)
        /home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20171105060200-01f8541d5372/go/otgrpc/server.go:61 +0x375
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Diff_Handler(0x1405c80, 0xc000510480, 0x1744a20, 0xc0002764b0, 0xc000072ae0, 0xc0000e7740, 0x1744a20, 0xc0002764b0, 0xc00015aa80, 0x957)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.9.1/sdk/proto/go/provider.pb.go:1599 +0x152
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000cc000, 0x1753fe0, 0xc00005be00, 0xc000197200, 0xc000521aa0, 0x207f218, 0x0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995 +0x467
    google.golang.org/grpc.(*Server).handleStream(0xc0000cc000, 0x1753fe0, 0xc00005be00, 0xc000197200, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275 +0xd9e
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000374330, 0xc0000cc000, 0x1753fe0, 0xc00005be00, 0xc000197200)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710 +0xc2
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:708 +0xa8
```

If I were to replace `dropletIds: [mainDroplet.id.apply(parseInt)]` with `dropletIds: []`, my `pulumi preview` is normal. I can work around this by destroying my stack and redeploying a fresh one, but I don't always want to have to bring down my entire stack for this.

**Comment by matthewswar** [comment]
Following up on my previous message, I don't appear to be getting that error anymore and I can do a `pulumi up` when there are existing Firewall resources using the `dropletId`. Will follow up again if I run into it, but I assume that the [latest merge](https://github.com/pulumi/pulumi-digitalocean/commit/8927c09c7d3551c997386f07b3ed098f3636a7c6) fixed something.

**Comment by CanRau** [comment]
Trying the `parseInt` conversion I get

```
panic: interface conversion: interface {} is string, not int
```

setting `dropletIds: []` let's me deploy, then I can use the actual values, though just now trying to update I had to fallback to commenting out the actual values for it to work again 👀
